# Site settings
title: Documentation
author:
  name: Sébastien Wauquier
  email: sw@cwantic.com
description: "All you need to know about MetaPiping"

# Build settings
remote_theme: just-the-docs/just-the-docs 

color_scheme: light

callouts:
  warning:
    title: Warning
    color: red

# MathJax (LaTeX)
mathjax:
  source: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_SVG"
  config: >
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        displayMath: [['$$','$$'], ['\\[','\\]']]
      },
      TeX: {
        equationNumbers: { autoNumber: "AMS" }
      },
      SVG: { mtextFontInherit: true }
    });
