# Site settings
title: MetaPiping documentation
author:
  name: Sébastien Wauquier
  email: sw@cwantic.com
description: "All you need to know about MetaPiping"

# Build settings
remote_theme: just-the-docs/just-the-docs 

color_scheme: light

#logo: "/Images/MetaPiping_web_title.png"